name: "Dive CI"

on: [push]

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: priyankachouk/dive@main
      - name: Build image
        run: docker build -t sample:latest -f node-starter/Dockerfile 
      - name: Dive
        uses: priyankachouk/dive@main
        with:
          image: "sample:latest"
          config-file: node-starter/.dive-ci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
