name: "Dive CI"

on: [push]

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t dive1:latest .
      - name: Dive Action
        uses: yuichielectric/dive-action@0.0.3
        with:
          image: "dive1:latest"
          config-file: ${{ github.workspace }}/.dive.yaml
          github-token: ${{ secrets.GITHUB_TOKEN }}
