name: "Dive CI"

on: [push]

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t sample1:latest .
      - name: pwd
        run: pwd && ls
      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: "sample1:latest"
          config-file: /home/runner/work/dive/dive/.dive-ci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
